[versions]
forge-gradle = "[6.0.36,6.2)"
neoforge-gradle = "2.0.+"
mixin-gradle = "0.7.+"
parchment = "1.+"
lombok = "1.18.+"
lwjgl = "3.4.+"
slf4j = "2.0.+"
findbugs = "3.0.+"
mixin = "0.8.+"

[plugins]
forge = { id = "net.minecraftforge.gradle", version.ref = "forge-gradle" }
neoforge = { id = "net.neoforged.moddev", version.ref = "neoforge-gradle" }
parchment = { id = "org.parchmentmc.librarian.forgegradle", version.ref = "parchment" }
mixin = { id = "org.spongepowered.mixin", version.ref = "mixin-gradle" }

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
glfw = { module = "org.lwjgl:lwjgl-glfw", version.ref = "lwjgl" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
findbugs = { module = "com.google.code.findbugs:jsr305", version.ref = "findbugs" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
