modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Nekeras/borderless/issues"
clientSideOnly = true

[[mods]]
modId = "${modid}"
version = "${version}"
displayName = "Borderless Window"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/borderless"
logoFile = "logo.png"
authors = "Nekeras"
description = '''
Replaces the standard Minecraft fullscreen with a borderless window.
This allows to easily switch monitors when Minecraft is not focussed, without minimizing the game.
'''
displayTest = "IGNORE_ALL_VERSION"
